name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install setuptools
        run: |
          pip install -r requirements.txt
          pip install wheel

      - name: Extract tag name
        id: tag
        run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Update version
        run: |
          sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.tag.outputs.TAG_NAME }}/g" setup.py

      - name: Build wheel
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
