name: release

on:
  push:
    branches:
      - master

jobs:
  release_helper:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs.release_created }}
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      patch: ${{ steps.release.outputs.patch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: python

  release:
    runs-on: ubuntu-latest
    needs: release_helper
    if: ${{ needs.release_helper.outputs.release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare
        id: prepare
        run: |
          echo "::set-output name=version::${{ needs.release_helper.outputs.major }}.${{ needs.release_helper.outputs.minor }}.${{ needs.release_helper.outputs.patch }}"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install
        run: |
          pip install setuptools wheel
          pip install -r requirements.txt

      - name: Update version
        run: |
          sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.prepare.outputs.version  }}/g" setup.py

      - name: Build wheel
        run: |
          python setup.py sdist bdist_wheel

      - name: Publish 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.11.0
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
